# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfldata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterback',
            name='passing_attempts',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarterback',
            name='passing_completions',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
